### ISSUE TITLE
Background tabs crashes after a while when using WS

### ISSUE THREAD

**Issue by jorgeyp** [proteus-h2020/proteic#143]
D3 queues the DOM updates until the tab is in the foreground again, crashing the browser. Maybe we can fix it by using [visibilityChange](https://developer.mozilla.org/es/docs/Web/Events/visibilitychange) to stop calling the `draw()` method but keeping the WS alive and storing incoming data.

**Comment by 0xNacho** [comment]
Partially fixed in cece4b4ce0631402b8324e57ba1dff64a7f43b99
